orbs:
  gcp-gke: circleci/gcp-gke@1.1.0

version: 2.1

jobs:
  # build the project and prepare it for deployment
  test:
    docker:
      - image: circleci/node:12.18.4-browsers
    working_directory: ~/nasa
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm ci
      # cache node modules
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run lint
      - run: npm run test

workflows:
  build_test_deploy:
    jobs:
      - test
      # The build step is now in the Dockerfile
      # Since it's an Orb job I did not find a way to use a cached version of the
      # built app from a previous job like we do in `config.kops.yml`
      - gcp-gke/publish-and-rollout-image:
          context:
            - GKE
          cluster: experimental-cluster
          container: nasa
          deployment: node-api-starter-angular-app
          google-compute-zone: GKE_COMPUTE_ZONE
          image: gcr.io/unique-serenity-287315/feredean/node-api-starter-angular-app
          tag: $CIRCLE_SHA1
          filters:
            # only deploy when a commit hits the master branch
            branches:
              only: master
