apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api-starter-angular-app
spec:
  replicas: 1
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      app: node-api-starter-angular-app
      category: open-source
  template:
    metadata:
      labels:
        app: node-api-starter-angular-app
        category: open-source
    spec:
      nodeSelector:
      containers:
        - name: nasa
          image: feredean/node-api-starter-angular-app
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: gcr-secret
